version: "1"
services:
  - type: web
    name: probabilistic-engine
    runtime: python
    repo: https://github.com/proxytransfer/ict-intelligence-backend-v2
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
